version: '3.8'
services:
  flask:
    image: pyflask
    container_name: pyflask-docker
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/
    environment:
      - PORT=5000